spring:
  application:
    name: OfferGenerationService
  datasource:
    url: jdbc:postgresql://localhost:5432/offerDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

